FROM ubuntu:22.04

RUN apt-get update -y && apt-get install -y build-essential curl libjack-jackd2-dev libasound2 libasound2-dev portaudio19-dev ffmpeg
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="$PATH:/root/.local/bin"

WORKDIR /app
RUN uv venv --python 3.10
COPY pyproject.toml uv.lock ./
RUN uv sync --extra frontend
COPY frontend ./frontend
CMD ["uv", "run", "streamlit", "run", "--server.port=8501", "--server.address=0.0.0.0", "frontend/stl_app.py", "--", "--docker"]
