name: voiceapi
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    ports:
      - "8000:8000"
    depends_on: # TODO: check dependency
      - vad
      - asr

  vad:
    build:
      context: .
      dockerfile: docker/Dockerfile.vad
    volumes:
      - ./models:/app/models:ro
    environment:
      - PUSH_PORT=tcp://*:8002
      - PULL_PORT=tcp://app:8001

  asr:
    build:
      context: .
      dockerfile: docker/Dockerfile.asr
    volumes:
      - ./models:/app/models:ro
    environment:
      - PUSH_PORT=tcp://*:8003
      - PULL_PORT=tcp://vad:8002

networks:
  default:
    driver: bridge
