name: voiceapi
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    environment:
      - PULL_PORT=tcp://asr:8003
    container_name: app
    ports:
      - "8000:8000"
    depends_on: # TODO: check dependency
      - vad
      - asr

  vad:
    build:
      context: .
      dockerfile: docker/Dockerfile.vad
    volumes:
      - ./models:/app/models:ro
    environment:
      - PULL_PORT=tcp://app:8001
    container_name: vad

  asr:
    build:
      context: .
      dockerfile: docker/Dockerfile.asr
    volumes:
      - ./models:/app/models:ro
    environment:
      - PULL_PORT=tcp://vad:8002
    container_name: asr

networks:
  default:
    driver: bridge
