name: voiceapi
services:
  # Frontend
  streamlit:
    build:
      context: .
      dockerfile: frontend/docker/Dockerfile.streamlit
    ports:
      - "8501:8501"
    devices:
      - /dev/snd:/dev/snd
    # volumes:
    #   - /dev/shm:/dev/shm
    environment:
      - ALSA_CARD=Generic_1
    # group_add:
    #   - audio
    depends_on:
      - app

  # Backend
  app:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.app
    ports:
      - "8000:8000"
    depends_on: # TODO: check dependency
      - vad
      - asr
      - sid

  vad:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.sherpa
    runtime: nvidia
    volumes:
      - ./models:/app/models:ro
    environment:
      - PUSH_PORT=tcp://*:8002
      - PULL_PORT=tcp://app:8001
    command: uv run backend/vad.py --docker --provider cuda

  asr:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.sherpa
    runtime: nvidia
    volumes:
      - ./models:/app/models:ro
    environment:
      - PUSH_PORT=tcp://*:8003
      - PULL_PORT=tcp://vad:8002
    command: uv run backend/asr.py --docker --provider cuda

  sid:
    build:
      context: .
      dockerfile: backend/docker/Dockerfile.sherpa
    runtime: nvidia
    volumes:
      - ./models:/app/models:ro
    environment:
      - PUSH_PORT=tcp://*:8004
      - PULL_PORT=tcp://vad:8002
    command: uv run backend/sid.py --docker --provider cuda

networks:
  default:
    driver: bridge
